#include <inttypes.h>
#include <string.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "pins.h"
#include "esp_check.h"
#include "esp_log.h"

#include "driver/i2s_pdm.h"
#include "driver/gpio.h"

#include "player.h"
#include "audio.h"
#include "slot.h"
#include "vm.h"
#include "variables.h"
#include "schedule.h"
#include "logger.h"

#define TAG "PLAYER"

#define SOUND_CHANNELS 8

#define PDM_TX_CLK_IO           I2S_BCLK_IO1      // I2S PDM TX clock io number
#define PDM_TX_DOUT_IO          I2S_DOUT_IO1      // I2S PDM TX data out io number

typedef struct SoundChannel {
    Slot *slot;
    uint8_t subslot;
    /* channel is acquired when file is not NULL */
    WaveFile *file;
    uint32_t delay;
    uint32_t volume_step;
    uint32_t volume_timer;
    uint8_t volume_cur;
    bool aborted;
} SoundChannel;

static SoundChannel channels[SOUND_CHANNELS];
/* Limited by DMA buffer size=2046 */
#define BUFFER_SIZE 2000
static uint16_t buffer[BUFFER_SIZE];
i2s_chan_handle_t tx_chan;
static bool player_on = true;


bool player_is_on(void)
{
    return player_on;
}

void player_set_onoff(bool onoff)
{
    player_on = onoff;
}

static void player_clear_channel(SoundChannel *ch)
{
    if (ch->file) {
        wave_close(ch->file);
    }
    if (!ch->aborted && ch->slot) {
        slot_finished_sound(ch->slot, ch->subslot);
    }
    ch->file = NULL;
    ch->delay = 0;
    ch->aborted = false;
    ch->slot = NULL;
}

static void player_mixer_task(void *args)
{
    while (true) {
        uint16_t count = BUFFER_SIZE;
        uint16_t last = 0;
        for (last = 0 ; last < count ; ++last) {
            bool found = false;
            /* Requires three volume multiplications */
            int32_t s = 0;
            for (int i = 0 ; i < SOUND_CHANNELS ; ++i) {
retry:
                if (channels[i].file || channels[i].delay) {
                    int16_t v;
                    bool clear = false;
                    if (channels[i].aborted) {
                        clear = true;
                    } else if (channels[i].delay) {
                        if (!--channels[i].delay) {
                            clear = true;
                        } else {
                            found = true;
                        }
                    } else if (!wave_next_sample(channels[i].file, &v)) {
                        clear = true;
                    } else {
                        found = true;
                        s += v * channels[i].volume_cur;
                        if (channels[i].volume_step) {
                            if (!--channels[i].volume_timer) {
                                channels[i].volume_timer = channels[i].volume_step;
                                ++channels[i].volume_cur;
                            }
                        }
                    }
                    if (clear) {
                        player_clear_channel(&channels[i]);
                        /* Switch to other tasks to allow continuous playing
                           by starting next sample. */
                        vTaskDelay(pdMS_TO_TICKS(10));
                        /* Try to get rid of empty sample between files */
                        goto retry;
                    }
                }
            }
            if (!found) {
                break;
            }
            /* Divide by 100% volume */
            s /= 128;
            if (s > 32767) {
                s = 32767;
            } else if (s < -32767) {
                s = -32767;
            }
            /* Don't skip all the sounds, because they affect the behavior */
            if (!player_on) {
                s = 0;
            }
            buffer[last] = s;
        }
        if (last) {
            /* TODO: check timeout and retry? */
            if (i2s_channel_write(tx_chan, buffer, last * sizeof(uint16_t), NULL, 1000) != ESP_OK) {
                printf("Write Task: i2s write failed\n");
            }
        } else {
            vTaskDelay(pdMS_TO_TICKS(10));
        }
    }
}

void player_init(void)
{
    if (!wave_get_samplerate()) {
        logger_printf("Project was not initialized, skipping player initialization");
        return;
    } else {
        logger_printf("Initializing player with samplerate %d", wave_get_samplerate());
    }
    /* I2S */
    i2s_chan_config_t tx_chan_cfg = I2S_CHANNEL_DEFAULT_CONFIG(I2S_NUM_AUTO, I2S_ROLE_MASTER);
    tx_chan_cfg.auto_clear = true;
    tx_chan_cfg.dma_desc_num = 4;
    tx_chan_cfg.dma_frame_num = BUFFER_SIZE;
    ESP_ERROR_CHECK(i2s_new_channel(&tx_chan_cfg, &tx_chan, NULL));

    /* Step 2: Setting the configurations of PDM TX mode and initialize the TX channel
     * The slot configuration and clock configuration can be generated by the macros
     * These two helper macros is defined in 'i2s_pdm.h' which can only be used in PDM TX mode.
     * They can help to specify the slot and clock configurations for initialization or re-configuring */
    i2s_pdm_tx_config_t pdm_tx_cfg = {
        .clk_cfg = I2S_PDM_TX_CLK_DEFAULT_CONFIG(wave_get_samplerate()),
        /* The data bit-width of PDM mode is fixed to 16 */
        .slot_cfg = I2S_PDM_TX_SLOT_DEFAULT_CONFIG(I2S_DATA_BIT_WIDTH_16BIT, I2S_SLOT_MODE_MONO),
        .gpio_cfg = {
            .clk = PDM_TX_CLK_IO,
            .dout = PDM_TX_DOUT_IO,
            .invert_flags = {
                .clk_inv = false,
            },
        },
    };
    ESP_ERROR_CHECK(i2s_channel_init_pdm_tx_mode(tx_chan, &pdm_tx_cfg));

    /* Step 3: Enable the tx channel before writing data */
    ESP_ERROR_CHECK(i2s_channel_enable(tx_chan));

    xTaskCreatePinnedToCore(player_mixer_task, "player_task", 2560, 0, 5, NULL, 1);
}

void player_clear(void)
{
    for (int i = 0 ; i < SOUND_CHANNELS ; ++i) {
        player_clear_channel(&channels[i]);
    }
}

void player_abort_slot(Slot *slot, uint8_t subslot)
{
    for (int i = 0 ; i < SOUND_CHANNELS ; ++i) {
        if (channels[i].slot == slot && channels[i].subslot == subslot) {
            channels[i].aborted = true;
            break;
        }
    }
}

static SoundChannel *player_acquire_channel(Slot *slot, uint8_t subslot)
{
    /* TODO: work with priorities */
    for (int i = 0 ; i < SOUND_CHANNELS ; ++i) {
        if (!channels[i].file && !channels[i].delay && !channels[i].aborted) {
            channels[i].slot = slot;
            channels[i].subslot = subslot;
            return &channels[i];
        }
    }
    return NULL;
}

void play_slot_delay(Slot *slot, uint8_t subslot, uint8_t delay)
{
    logger_printf(TAG " DELAY %d in %d/%d", delay, slot->id, subslot);
    SoundChannel *ch = player_acquire_channel(slot, subslot);
    if (!ch) {
        logger_printf(TAG " No available slots");
        return;
    }
    ch->delay = (delay * wave_get_samplerate()) / 1000;
    slot_started_delay(slot, subslot);
}

void play_slot_sound(Slot *slot, uint8_t subslot, uint16_t id,
                     uint8_t volmin, uint8_t volmax)
{
    logger_printf(TAG " PLAY %d in %d/%d", id, slot->id, subslot);
    SoundChannel *ch = player_acquire_channel(slot, subslot);
    if (!ch) {
        logger_printf(TAG " No available slots");
        return;
    }
    ch->file = wave_open(id);
    if (!ch->file) {
        logger_printf(TAG " Can't open wave file %d in %d/%d", id, slot->id, subslot);
        return;
    }
    ch->volume_cur = volmin;
    if (volmax != volmin) {
        uint32_t samples = wave_get_length(ch->file);
        samples /= volmax - volmin;
        ch->volume_step = samples;
        ch->volume_timer = samples;
    } else {
        ch->volume_step = 0;
        ch->volume_timer = 0;
    }
    ch->delay = 0;
    slot_started_sound(slot, subslot);
}
